language: node_js
node_js:
- '5'
- '6'
before_install: npm install -g gulp
install: npm install
before_script: gulp lint
script: gulp test
before_deploy: gulp package
deploy:
  provider: releases
  file: tmp/release.tar.gz
  skip_cleanup: true
  on:
    repo: lukvonstrom/Amethyst
    tags: true
    all_branches: true
    node: '6'
after_success:
  - gulp coveralls
