language: node_js
node_js:
- '5'
- '6'
before_install: npm install -g gulp node-pre-gyp
install: npm install
before_script: gulp lint
script: gulp test
before_deploy: gulp package
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: releases
  file: tmp/release.tar.gz
  skip_cleanup: true
  on:
    repo: LukvonStrom/Amethyst
    tags: true
    all_branches: true
    node: '6'
after_success:
  - gulp coveralls
